### ISSUE TITLE
hw 0 - mark

### ISSUE THREAD

**Issue by MaximUshakov** [yandexdataschool/HSE_deeplearning#4]
Hi!

I sent my homework from maskimka3@gmail.com at 21.57 on Wensday, 28/09/2016. I sent another email (21/11/2016) when I didn't found myself in the grade sheet, but there was no answer. So I've posted an issue here.

**Comment by justheuristic** [comment]
We're sorry, the mails are nowhere to be found. Could you please attach both HWs here (gist) or in slack?

**Comment by MaximUshakov** [comment]
Morning!

Do you recieve my email with both homeworks (2016-12-05)?

**Comment by justheuristic** [comment]
Yup, checked 'em
