### ISSUE TITLE
Were the seminars recorded?

### ISSUE THREAD

**Issue by roboserg** [yandexdataschool/HSE_deeplearning#69]
Would like to know whether the seminars (in Russian) were recorded for the 2019 course or will there be recordings of the seminars for the 2020 course?

**Comment by justheuristic** [comment]
Hi! Seminars are recorded and published in the respective seminar* folder's  README.md. Look for entries like this (the second one is a seminar)
![image](https://user-images.githubusercontent.com/3491902/78696113-a51b8e80-7907-11ea-8498-f75a22d8d9b9.png)

**Comment by roboserg** [comment]
@justheuristic yes, but seminars 3 4 and 5 are empty, hence my question whether or not you will add it some day?
